/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    insights: Insight;
    'success-stories': SuccessStory;
    services: Service;
    users: User;
    media: Media;
    topics: Topic;
    publications: Publication;
    'content-pipeline': ContentPipeline;
    'content-variants': ContentVariant;
    knowledge: Knowledge;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    insights: InsightsSelect<false> | InsightsSelect<true>;
    'success-stories': SuccessStoriesSelect<false> | SuccessStoriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    'content-pipeline': ContentPipelineSelect<false> | ContentPipelineSelect<true>;
    'content-variants': ContentVariantsSelect<false> | ContentVariantsSelect<true>;
    knowledge: KnowledgeSelect<false> | KnowledgeSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword:
    | {
        email: string;
      }
    | {
        username: string;
      };
  login:
    | {
        email: string;
        password: string;
      }
    | {
        password: string;
        username: string;
      };
  registerFirstUser: {
    password: string;
    username: string;
    email?: string;
  };
  unlock:
    | {
        email: string;
      }
    | {
        username: string;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights".
 */
export interface Insight {
  id: number;
  title: string;
  slug: string;
  category:
    | 'ai-ml'
    | 'bi'
    | 'data-engineering'
    | 'data-strategy'
    | 'managed-data'
    | 'software-development'
    | 'technology'
    | 'case-study'
    | 'industry';
  summary?: string | null;
  readTime?: string | null;
  author?: {
    name?: string | null;
    title?: string | null;
    image?: (number | null) | Media;
  };
  heroImage?: {
    image?: (number | null) | Media;
  };
  sections?:
    | {
        type: 'text' | 'heading' | 'Chart' | 'image';
        content?: string | null;
        title?: string | null;
        variant?: string | null;
        image?: (number | null) | Media;
        data?:
          | {
              label?: string | null;
              value?: string | null;
              color?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socialShare?: boolean | null;
  relatedArticles?:
    | {
        title?: string | null;
        readTime?: string | null;
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  cta: {
    title: string;
    subtitle: string;
  };
  publishedDate: string;
  /**
   * Total number of likes for this insight
   */
  likes?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-stories".
 */
export interface SuccessStory {
  id: number;
  title: string;
  slug: string;
  category: 'bi' | 'ai' | 'data-engineering' | 'data-strategy' | 'managed-data';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image?: (number | null) | Media;
  excerpt?: string | null;
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  client?: string | null;
  challenge?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  solution?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  result?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  category: 'bi' | 'ai' | 'data-engineering' | 'data-strategy' | 'managed-data';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image?: (number | null) | Media;
  excerpt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  roles: ('user' | 'admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: number;
  title: string;
  problem: string;
  angle: string;
  audience?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  contentType?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  cta?: string | null;
  scores?: {
    authority?: number | null;
    leadGeneration?: number | null;
    evergreen?: number | null;
    youtubePotential?: number | null;
    overallScore?: number | null;
  };
  distributionTier?: string | null;
  recommendedPlatforms?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  contentPriority?: string | null;
  aiRecommendations?: {
    reasoning?: string | null;
    youtubeMode?: string | null;
    estimatedLeadPotential?: number | null;
  };
  status: 'generated' | 'approved' | 'rejected' | 'content-created';
  topicHash?: string | null;
  generatedBy?: ('ai' | 'human') | null;
  rawAIOutput?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  title: string;
  content: number | ContentPipeline;
  platform: 'linkedin' | 'facebook' | 'insights' | 'youtube' | 'instagram' | 'tiktok';
  externalId?: string | null;
  publishedUrl?: string | null;
  publishedAt?: string | null;
  status?: ('scheduled' | 'published' | 'failed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-pipeline".
 */
export interface ContentPipeline {
  id: number;
  title: string;
  topic: number | Topic;
  status?:
    | (
        | 'draft'
        | 'awaiting-content-approval'
        | 'content-approved'
        | 'awaiting-distribution-approval'
        | 'distribution-approved'
        | 'published'
        | 'rejected'
      )
    | null;
  coreMessage?: string | null;
  insightsArticle?: string | null;
  youtubeScript?: string | null;
  youtubeTitle?: string | null;
  youtubeDescription?: string | null;
  thumbnailIdeas?:
    | {
        idea?: string | null;
        id?: string | null;
      }[]
    | null;
  approvalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-variants".
 */
export interface ContentVariant {
  id: number;
  title: string;
  content: number | ContentPipeline;
  platform: 'linkedin' | 'facebook' | 'instagram' | 'tiktok' | 'youtube';
  contentBody?: string | null;
  version?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge".
 */
export interface Knowledge {
  id: number;
  title: string;
  documentType:
    | 'project'
    | 'case-study'
    | 'meeting-notes'
    | 'proposal'
    | 'architecture'
    | 'lesson-learned'
    | 'faq'
    | 'service';
  entryMethod?: ('manual' | 'document') | null;
  sourceDocument?: (number | null) | Media;
  industry?: string | null;
  services?:
    | (
        | 'ai-automation'
        | 'llm-engineering'
        | 'workflow-automation'
        | 'data-engineering'
        | 'business-intelligence'
        | 'system-integration'
      )[]
    | null;
  problem?: string | null;
  solution?: string | null;
  outcomes?:
    | {
        outcome?: string | null;
        id?: string | null;
      }[]
    | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  summary?: string | null;
  tags?: string[] | null;
  contentGenerationValue?: number | null;
  approvedForContentGeneration?: boolean | null;
  processingStatus?: ('pending' | 'processed' | 'failed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'insights';
        value: number | Insight;
      } | null)
    | ({
        relationTo: 'success-stories';
        value: number | SuccessStory;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'topics';
        value: number | Topic;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'content-pipeline';
        value: number | ContentPipeline;
      } | null)
    | ({
        relationTo: 'content-variants';
        value: number | ContentVariant;
      } | null)
    | ({
        relationTo: 'knowledge';
        value: number | Knowledge;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights_select".
 */
export interface InsightsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  summary?: T;
  readTime?: T;
  author?:
    | T
    | {
        name?: T;
        title?: T;
        image?: T;
      };
  heroImage?:
    | T
    | {
        image?: T;
      };
  sections?:
    | T
    | {
        type?: T;
        content?: T;
        title?: T;
        variant?: T;
        image?: T;
        data?:
          | T
          | {
              label?: T;
              value?: T;
              color?: T;
              id?: T;
            };
        id?: T;
      };
  socialShare?: T;
  relatedArticles?:
    | T
    | {
        title?: T;
        readTime?: T;
        imageUrl?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  publishedDate?: T;
  likes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-stories_select".
 */
export interface SuccessStoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  content?: T;
  image?: T;
  excerpt?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  client?: T;
  challenge?: T;
  solution?: T;
  result?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  content?: T;
  image?: T;
  excerpt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  title?: T;
  problem?: T;
  angle?: T;
  audience?: T;
  contentType?: T;
  cta?: T;
  scores?:
    | T
    | {
        authority?: T;
        leadGeneration?: T;
        evergreen?: T;
        youtubePotential?: T;
        overallScore?: T;
      };
  distributionTier?: T;
  recommendedPlatforms?: T;
  contentPriority?: T;
  aiRecommendations?:
    | T
    | {
        reasoning?: T;
        youtubeMode?: T;
        estimatedLeadPotential?: T;
      };
  status?: T;
  topicHash?: T;
  generatedBy?: T;
  rawAIOutput?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  platform?: T;
  externalId?: T;
  publishedUrl?: T;
  publishedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-pipeline_select".
 */
export interface ContentPipelineSelect<T extends boolean = true> {
  title?: T;
  topic?: T;
  status?: T;
  coreMessage?: T;
  insightsArticle?: T;
  youtubeScript?: T;
  youtubeTitle?: T;
  youtubeDescription?: T;
  thumbnailIdeas?:
    | T
    | {
        idea?: T;
        id?: T;
      };
  approvalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-variants_select".
 */
export interface ContentVariantsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  platform?: T;
  contentBody?: T;
  version?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge_select".
 */
export interface KnowledgeSelect<T extends boolean = true> {
  title?: T;
  documentType?: T;
  entryMethod?: T;
  sourceDocument?: T;
  industry?: T;
  services?: T;
  problem?: T;
  solution?: T;
  outcomes?:
    | T
    | {
        outcome?: T;
        id?: T;
      };
  content?: T;
  summary?: T;
  tags?: T;
  contentGenerationValue?: T;
  approvedForContentGeneration?: T;
  processingStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}